name: polmira-bot

services:
  polmira-bot:
    image: chtotos/polmira_bot:latest
    container_name: polmira-bot
    restart: unless-stopped
    privileged: true
    network_mode: host
    pid: host
    env_file:
      - /opt/polmira-docker/bot/.env
    environment:
      POLMIRA_BOT_ENV: /opt/polmira-docker/bot/.env
      POLMIRA_CMD: /app/host-polmira
      POLMIRA_APP_DIR: /opt/polmira-docker
      POLMIRA_USE_SUDO: "no"
    volumes:
      - /opt/polmira-docker:/opt/polmira-docker
      - ./bot:/opt/polmira-docker/bot:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/nginx:/etc/nginx
